# Generated by Django 5.2.4 on 2025-07-19 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenantId', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tenantName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], default='Active', max_length=10)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='tenant_profiles/')),
                ('address', models.TextField()),
                ('gstId', models.CharField(blank=True, max_length=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
